# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name:  Build & Publish To PyPi

on:
  workflow_dispatch:

    
jobs:
#   build-test-linux:

#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v2
#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: '3.9'
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install build
#           python3 -m pip install -r tests/requirements.txt
#       - name: Build package
#         run: python -m build
#       - name: Install package
#         run: pip install dist/*.whl
#       - name: Run tests
#         run: python setup.py test
        
#       - uses: actions/upload-artifact@v2
#         with:
#           name: dist
#           path: |
#             dist/*
  build-n-publish-to-testpypi:
    name: Build and publish Python ðŸ distributions ðŸ“¦ to TestPyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
      - name: Add artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist/*
            
      - name: Publish distribution ðŸ“¦ to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          
          
  test-pypi-ubuntu-latest-install:
    needs: build-n-publish-to-testpypi
    name: Test installing from TestPyPi on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          
      - name: Install TestPyPi Release
        run: pip install --index-url https://test.pypi.org/simple/  --extra-index-url https://pypi.org/simple pep-tk
        
      - name: Install test requirements
        run: pip install -r tests/requirements.txt
        
      - name: Run Tests on TestPyPi Release
        run:  python setup.py test
        
  test-pypi-windows-latest-install:
    needs: build-n-publish-to-testpypi
    name: Test installing from TestPyPi on windows-latest
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install TestPyPi Release
        run: pip install --index-url https://test.pypi.org/simple/  --extra-index-url https://pypi.org/simple pep-tk
        
      - name: Install test requirements
        run: pip install -r tests/requirements.txt
        
      - name: Run Tests on TestPyPi Release
        run:  python setup.py test
        
  publish-to-pypi:
    name: Publish To PyPi ðŸ“¦
    needs: [test-ubuntu-latest-install, test-windows-latest-install]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dist
      - name: ls
        run: |
          ls -R
          mkdir dist
          mv pep_tk* dist/
        
      - name: Publish distribution ðŸ“¦ to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
